// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedtKBfkoR0LXeFGoQcv2kGxwbnq2duJw',
    appId: '1:1028764636554:android:52ff5d45449531e1da2473',
    messagingSenderId: '1028764636554',
    projectId: 'characters-vault-4cab1',
    databaseURL: 'https://characters-vault-4cab1-default-rtdb.firebaseio.com',
    storageBucket: 'characters-vault-4cab1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iRRfgFHkoMoGjWREUDDazKOUA6PqIg4',
    appId: '1:1028764636554:ios:3ec4c46667b7dd47da2473',
    messagingSenderId: '1028764636554',
    projectId: 'characters-vault-4cab1',
    databaseURL: 'https://characters-vault-4cab1-default-rtdb.firebaseio.com',
    storageBucket: 'characters-vault-4cab1.appspot.com',
    androidClientId: '1028764636554-uv09hc41pcaou95uuk9t4pa44b513tqu.apps.googleusercontent.com',
    iosClientId: '1028764636554-gd0etnvmu73up59qh43ud856nk3gnirk.apps.googleusercontent.com',
    iosBundleId: 'com.example.characterVault',
  );

}