// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnVNm3oEI6WCVXJ5oP16AmCdkqga0gHI',
    appId: '1:386541822660:android:378553fd61b4a006d4df91',
    messagingSenderId: '386541822660',
    projectId: 'char-vault',
    databaseURL: 'https://char-vault-default-rtdb.firebaseio.com',
    storageBucket: 'char-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9QZHj9kXDiN2yCvgMGOBGTOTh94kEGo',
    appId: '1:386541822660:ios:964c3163b56593a0d4df91',
    messagingSenderId: '386541822660',
    projectId: 'char-vault',
    databaseURL: 'https://char-vault-default-rtdb.firebaseio.com',
    storageBucket: 'char-vault.appspot.com',
    androidClientId: '386541822660-b53pi2ebojvvdvak6oas69ujvp3hkll6.apps.googleusercontent.com',
    iosClientId: '386541822660-l0pjgp15ui7ot8snmi7e84o5f20bni6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.characterVault',
  );

}